### ISSUE TITLE
Correct street names in Frauenstein, Carinthia

### ISSUE THREAD

**Issue by thomaskonrad** [thomaskonrad/bev-reverse-geocoder#2]
See https://github.com/JOSM/austriaaddresshelper/issues/11.

**Comment by ChrisEt** [comment]
I see that this correction is only applied to street names in Frauenstein - are you sure this is the only municipality in Austria having this problem?

**Comment by thomaskonrad** [comment]
Yes I am, I searched the whole database for the same pattern. Only Frauenstein seems to apply it. If I do that correction for the whole DB, it takes very long.

The BEV Reverse Geocoder now returns correct street names ([example](https://bev-reverse-geocoder.thomaskonrad.at/reverse-geocode/json?lat=46.814002&lon=14.363844&distance=50&limit=3&epsg=4326)).

**Comment by ChrisEt** [comment]
Oh great, thanks a lot! :thumbsup:
(As a side note, I will see to it the wrong street names get corrected in OSM)
